server:
 port: 7001
eureka:
  client:
    fetch-registry: false # 是否要从Eureka中获取注册信息
    register-with-eureka: false #是否要注册到Eureka
  instance: # eureka实例定义
    hostname: localhost # 定义 Eureka 实例所在的主机名称
