server:
 port: 9000

eureka:
  client:
    register-with-eureka: false
    service-url:
        defaultZone: http://admin:111222@eurekaserver1:7001/eureka,http://admin:111222@eurekaserver2:7002/eureka,http://admin:111222@eurekaserver3:7003/eureka