server:
 port: 8081

spring:
 application:
   name: springclouddemo-provider

eureka:
  client: # 注册服务到Eureka
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    instance-id: microcloud-provider-product
    prefer-ip-address: true

info:
  app.name: springclouddemo-provider
  company.name: study
  build.artifactId: $project.artifactId$
  build.modelVersion: $project.modelVersion$
