server:
 port: 8083

spring:
 application:
   name: springclouddemo-provider

eureka:
  client:
    register-with-eureka: true # 注册服务到Eureka
    service-url:
      defaultZone: http://admin:111222@eurekaserver1:7001/eureka
  instance:
    instance-id: springclouddemo-provider3
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 2 # 设置心跳的时间间隔（默认是30秒）
    lease-expiration-duration-in-seconds: 5  # 如果现在超过了5秒的间隔（默认是90秒）

info:
  app.name: springclouddemo-provider
  company.name: study
  build.artifactId: $project.artifactId$
  build.modelVersion: $project.modelVersion$
