server:
 port: 7001
eureka:
  server:
    eviction-interval-timer-in-ms: 1000   #设置清理的间隔时间，而后这个时间使用的是毫秒单位（默认是60秒）
    enable-self-preservation: false #设置为false表示关闭保护模式
  client:
    fetch-registry: false # 是否要从Eureka中获取注册信息
    register-with-eureka: false #是否要注册到Eureka
    service-url:
        defaultZone: http://admin:111222@eurekaserver1:7001/eureka,http://admin:111222@eurekaserver2:7002/eureka,http://admin:111222@eurekaserver3:7003/eureka
  instance: # eureka实例定义
    hostname: eurekaserver1 # 定义 Eureka 实例所在的主机名称

spring:
  security:
    user:
      name: admin
      password: 111222